/**
 * C-115 — 「스켈레톤 읽기가 `oneOf` 를 «가지 키»로 내려가는가」. 대상을 IMPORT 합니다.
 *
 * 🔴 TWO SUBJECTS, ONE READER. The shipped chain skeleton (`server/chain_skeleton.json`, a
 *    tracked file generated by `chain_bindings.skeleton()`) holds two oneOf nodes whose
 *    branches are records and leaves -- it nests no oneOf under a oneOf today. The nesting
 *    claim is the GRAMMAR's, not that document's, so it is scored on a hand fixture and said
 *    to be one; the shipped document scores the descent today's screens actually take, so a
 *    branch removed from the generator reddens this from the client side.
 *
 * 🔴 THE EMPTY OF A oneOf IS 「NOTHING PICKED」 = `{}`. The same fact three ways: the renderer
 *    draws no branch for a value that names none, the loader (`rule_shape.from_declaration`)
 *    folds it to kind "unknown", and the grammar spells a oneOf's value as a mapping with the
 *    branch under its key. Before C-115 a required oneOf fell through to the leaf tail and was
 *    seeded `''` -- drawn the same, loaded the same, and a string where a mapping belongs. That
 *    regression is pinned here because nothing on screen would show it.
 *
 * Run:  node client2/tests/skeleton_oneof_descent_harness.mjs [--mutate]
 */
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { loadWithProbe } from './lib/probe.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..', '..');
const SRC = join(HERE, '..', 'src', 'ontology_skeleton.js');
const CHAIN_FILE = join(ROOT, 'server', 'chain_skeleton.json');

let pass = 0, quiet = false;
const failures = [];
const ok = (cond, name, detail = '') => {
  if (cond) { pass += 1; if (!quiet) console.log(`  OK   ${name}`); }
  else { failures.push(name); if (!quiet) console.log(`  BAD  ${name}${detail ? ' — ' + detail : ''}`); }
};
const show = (v) => (v === null || v === undefined ? String(v) : JSON.stringify(v));

const CHAIN = JSON.parse(readFileSync(CHAIN_FILE, 'utf8'));

// ── the nesting fixture ─────────────────────────────────────────────────────────────────
// A oneOf under a oneOf, one branch of which is a `{use}` -- the shipped grammar allows both
// and ships neither, so this is the only place the claim can be measured. Its keys exist
// nowhere in the product on purpose: a reader that answered from a written-down path could
// not answer for these.
const DEFS = {
  shared: {
    kind: 'record',
    fields: [{ key: 'inside', required: true,
      node: { kind: 'map', keyed_by: 'name', of: { kind: 'leaf', hint: 'free' } } }],
  },
};
const NESTED = {
  kind: 'record',
  fields: [
    { key: 'pick', required: true, node: { kind: 'oneOf', hint: 'choice', branches: {
      outer_a: { kind: 'oneOf', hint: 'choice', branches: {
        inner_x: { kind: 'leaf', hint: 'ref' },
        inner_y: { use: 'shared' },
      } },
      outer_b: { kind: 'leaf', hint: 'free' },
    } } },
    { key: 'name', required: true, node: { kind: 'leaf', hint: 'free' } },
    { key: 'flag', required: true, node: { kind: 'leaf', hint: 'flag' } },
  ],
};

function suite(M) {
  const before = failures.length;

  // ══ ① 출하된 스켈레톤 — 오늘 화면이 «실제로» 내려가는 길 ═══════════════════════════════
  const root = CHAIN.unified_root;
  const defs = CHAIN.defs;
  const at = (steps) => M.shapeAt(root, steps, defs);
  const derive = at(['derive']);
  ok(derive && derive.kind === 'oneOf',
    'D1 the shipped `derive` cell is a oneOf — the subject exists', show(derive && derive.kind));
  const rightTable = at(['derive', 'join', 'right_table']);
  ok(rightTable && rightTable.kind === 'leaf',
    'D2 shapeAt reaches a field INSIDE the picked branch — derive.join.right_table',
    show(rightTable));
  const table = at(['into', 'table']);
  ok(table && table.kind === 'leaf' && table.hint === 'ref',
    'D3 ...and a leaf branch is the shape at its own key (ruling 411), not a record around it',
    show(table));
  // 🔴 THE CONTROLS. Without them a reader that answered for any key would satisfy D2-D3.
  ok(at(['derive', 'no_such_branch']) === null,
    'D4 CONTROL: a branch the skeleton does not declare resolves to nothing');
  ok(at(['derive', 'join', 'right_table', 'deeper']) === null,
    'D5 CONTROL: nothing lives under a leaf, inside a branch or not');

  // ══ ② oneOf 안의 oneOf — 문법의 주장 ═══════════════════════════════════════════════════
  const inner = M.shapeAt(NESTED, ['pick', 'outer_a', 'inner_x'], DEFS);
  ok(inner && inner.kind === 'leaf' && inner.hint === 'ref',
    'N1 a oneOf nested under a oneOf: shapeAt reaches the inner branch\'s leaf', show(inner));
  const innerOneOf = M.shapeAt(NESTED, ['pick', 'outer_a'], DEFS);
  ok(innerOneOf && innerOneOf.kind === 'oneOf',
    'N2 ...and stopping one step short hands back the inner oneOf itself', show(innerOneOf && innerOneOf.kind));
  const viaUse = M.shapeAt(NESTED, ['pick', 'outer_a', 'inner_y', 'inside'], DEFS);
  ok(viaUse && viaUse.kind === 'map',
    'N3 a `{use}` branch is followed like any other node, and walked through', show(viaUse));
  ok(M.shapeAt(NESTED, ['pick', 'inner_x'], DEFS) === null,
    'N4 CONTROL: descent is by key at EACH level — an inner key is not found from the outer one');

  // ══ ③ 빈 값 — 「안 고름」 ═══════════════════════════════════════════════════════════════
  const emptyOuter = M.emptyOf(M.shapeAt(NESTED, ['pick'], DEFS), DEFS);
  ok(JSON.stringify(emptyOuter) === '{}' && !Array.isArray(emptyOuter),
    'E1 the empty of a oneOf is an object holding no branch key — nothing picked', show(emptyOuter));
  const emptyInner = M.emptyOf(innerOneOf, DEFS);
  ok(JSON.stringify(emptyInner) === '{}' && !Array.isArray(emptyInner),
    'E2 ...and so is the empty of the nested one', show(emptyInner));
  const seed = M.emptyOf(NESTED, DEFS);
  ok(JSON.stringify(seed.pick) === '{}' && seed.flag === false
    && !Object.prototype.hasOwnProperty.call(seed, 'name'),
  'E3 a record seeds a required oneOf as a held-but-unpicked container, beside the leaf rules unchanged',
  show(seed));
  const shipped = M.emptyOf(root, defs);
  ok(JSON.stringify(shipped.derive) === '{}' && JSON.stringify(shipped.into) === '{}',
    'E4 the shipped new-rule seed holds derive and into as unpicked mappings, not strings',
    show(shipped));
  // 🔴 THE CONTROL: the oneOf answer is not "everything became `{}`".
  ok(M.emptyOf(M.shapeAt(NESTED, ['pick', 'outer_b'], DEFS), DEFS) === '',
    'E5 CONTROL: a leaf branch still empties as the leaf does');
  const chosen = M.emptyOf(M.shapeAt(NESTED, ['pick', 'outer_a', 'inner_y'], DEFS), DEFS);
  ok(JSON.stringify(chosen) === '{"inside":{}}',
    'E6 the chosen branch\'s empty is the branch node\'s own — what the picker writes under the key',
    show(chosen));

  return { fail: failures.length - before };
}

console.log('-- oneOf descent, read off the shipped chain skeleton and a nested fixture ------');
suite(await import('../src/ontology_skeleton.js'));
const base = { pass, fail: failures.length };
console.log(`\n${base.fail === 0 ? '✓' : '✗'} baseline: ${base.pass} passed, ${base.fail} failed`);
console.log(`ASSERTIONS ${base.pass + base.fail} ${base.fail}`);

const DEFECTS = [
  ['oneOf stops being descended, so a field inside a picked branch is unreachable',
    (s) => s.replace("  if (node.kind === 'oneOf') {", '  if (false) {')],
  ['a branch is found for any key, so a control resolves to the first branch',
    (s) => s.replace('    return branch ? deref(branch, defs) : null;',
                     '    return deref(Object.values(branches)[0] || null, defs);')],
  ['a oneOf empties to the leaf tail again, so a required oneOf is seeded as a string',
    (s) => s.replace("  if (shape.kind === 'oneOf') return {};", '')],
];
const CONTROLS = [
  ['comments stripped', (s) => s.split('\n').filter((l) => !/^\s*(\/\/|\*|\/\*)/.test(l)).join('\n')],
];

if (process.argv.includes('--mutate')) {
  quiet = true;
  let caught = 0; const wrong = [];
  console.log('\n-- defect mutants (each must be CAUGHT) ------------------------------');
  for (const [name, mutate] of DEFECTS) {
    let r;
    try { r = suite((await loadWithProbe(SRC, { mutate, tag: 'oneofd' })).module); }
    catch (e) {
      if (/did not mutate|unchanged/.test(String(e && e.message))) {
        quiet = false; console.error(`  anchor GONE: ${name} — ${e.message}`); process.exit(2);
      }
      r = { fail: 1 };
    }
    if (r.fail > 0) { caught += 1; console.log(`  caught  ${name}`); }
    else { wrong.push(name); console.log(`  ESCAPED ${name}`); }
  }
  console.log('\n-- control mutants (each must ESCAPE) --------------------------------');
  for (const [name, mutate] of CONTROLS) {
    let r;
    try { r = suite((await loadWithProbe(SRC, { mutate, tag: 'oneofc' })).module); }
    catch { r = { fail: 1 }; }
    if (r.fail === 0) console.log(`  escaped ${name}`);
    else { wrong.push(`control caught: ${name}`); console.log(`  CAUGHT  ${name} <- control caught`); }
  }
  quiet = false;
  console.log(`\nmutations: ${caught}/${DEFECTS.length} caught`);
  if (wrong.length) { console.error(`wrong verdicts:\n  ${wrong.join('\n  ')}`); process.exit(1); }
}

process.exit(base.fail === 0 ? 0 : 1);
