import asyncio
import json
import os
import logging
import importlib
import uuid
from collections import defaultdict

# Logger setup
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("ChainIngestionWorker")

RULES_PATH = os.path.join(os.path.dirname(__file__), "config", "chain_rules.json")

def load_chain_rules():
    if not os.path.exists(RULES_PATH):
        logger.warning(f"Chain rules configuration file not found at {RULES_PATH}. Using empty rules.")
        return []
    try:
        with open(RULES_PATH, "r", encoding="utf-8") as f:
            data = json.load(f)
            return data.get("rules", [])
    except Exception as e:
        logger.error(f"Failed to load chain rules: {e}")
        return []

def execute_custom_mapper(module_name: str, function_name: str, db, payload):
    """
    Dynamically imports a python mapper module and executes the mapping function.
    """
    try:
        module = importlib.import_module(module_name)
        mapper_func = getattr(module, function_name)
        return mapper_func(db, payload)
    except Exception as e:
        logger.error(f"Error executing custom mapper {module_name}.{function_name}: {e}")
        raise e

async def process_chain_transaction_group(tx_id, events, db, rules):
    # 1. Filter out events already generated by chain_ingestion to prevent circular loops
    valid_events = [e for e in events if e.payload.get("source_name") != "chain_ingestion"]
    if not valid_events:
        return True

    # 2. Map of updates grouped by target table
    # target_table -> list of GeneralUpdateItem dicts
    table_updates = defaultdict(list)
    
    # 3. Evaluate rules for all events under this transaction
    for event in valid_events:
        event_type = event.event_type
        table_name = event.table_name
        payload = event.payload
        
        if event_type not in ["CREATE", "EDIT"]:
            continue

        matched_rules = [r for r in rules if r.get("trigger_table") == table_name and r.get("enabled", True)]
        for rule in matched_rules:
            target_table = rule.get("target_table")
            module_name = rule.get("mapper_module")
            func_name = rule.get("mapper_function")
            
            try:
                # Execute dynamic mapper function
                target_payload = execute_custom_mapper(module_name, func_name, db, payload)
                if target_payload and target_payload.get("updates"):
                    # Consolidate updates list
                    table_updates[target_table].extend(target_payload.get("updates"))
            except Exception as e:
                logger.error(f"Failed to execute mapper in tx {tx_id} for rule '{rule.get('name')}': {e}")
                return False

    # 4. Perform chained batch updates by target table
    if table_updates:
        from database import schemas, crud
        from database.context import request_user, request_transaction_id, request_source
        
        token_user = request_user.set("chain_worker")
        token_tx = request_transaction_id.set(tx_id)
        token_src = request_source.set("chain_ingestion")
        
        try:
            for target_table, updates_list in table_updates.items():
                batch_data = schemas.GeneralUpdateBatch(
                    updates=updates_list,
                    transaction_id=tx_id,
                    silent=False
                )
                logger.info(f"Executing chained batch updates to '{target_table}' under tx '{tx_id}' (size: {len(updates_list)})")
                
                # Apply updates
                results, changed_cells, created_logs = crud.apply_batch_updates(db, target_table, batch_data)
                
                # 5. Broadcast real-time WebSocket events containing created_logs (Audit History)
                try:
                    from main import manager, inject_system_columns, to_local_str
                    
                    msg_items = []
                    for row, is_new in results:
                        inject_system_columns(row)
                        msg_items.append({
                            "row_id": row.row_id,
                            "is_new": is_new,
                            "data": row.data,
                            "created_at": to_local_str(row.created_at),
                            "updated_at": to_local_str(row.updated_at)
                        })
                        
                    user_name = "chain_worker"
                    
                    if len(msg_items) > 100:
                        msg = {
                            "event": "batch_refresh_required",
                            "table_name": target_table,
                            "change_count": len(msg_items),
                            "created_logs": created_logs
                        }
                    else:
                        msg = {
                            "event": "batch_row_upsert",
                            "table_name": target_table,
                            "items": msg_items,
                            "updated_by": user_name,
                            "created_logs": created_logs
                        }
                    
                    await manager.broadcast(json.dumps(msg))
                    logger.info(f"Successfully broadcasted chained update message for '{target_table}' under tx '{tx_id}'.")
                except Exception as ws_err:
                    logger.error(f"Failed to broadcast chained update WebSocket message: {ws_err}")
                    
        except Exception as e:
            logger.error(f"Failed executing chained batch update for tx {tx_id}: {e}")
            return False
        finally:
            request_user.reset(token_user)
            request_transaction_id.reset(token_tx)
            request_source.reset(token_src)
            
    return True

async def start_chain_ingestion_worker(db_session_factory):
    logger.info("Initializing Chained Ingestion Worker Daemon...")
    rules = load_chain_rules()
    logger.info(f"Loaded {len(rules)} active chain ingestion rules.")
    
    import sys
    script_dir = os.path.dirname(os.path.abspath(__file__))
    if script_dir not in sys.path:
        sys.path.append(script_dir)
        
    while True:
        try:
            db = db_session_factory()
            try:
                from database.models import DatabaseOutbox
                # Fetch pending outbox records
                pending_events = db.query(DatabaseOutbox).filter(
                    DatabaseOutbox.processed_chain == False
                ).order_by(DatabaseOutbox.id.asc()).limit(200).all()
                
                if not pending_events:
                    await asyncio.sleep(1)
                    continue
                
                # Group events by transaction_id
                groups = defaultdict(list)
                group_order = []
                
                for event in pending_events:
                    tx_id = event.payload.get("transaction_id")
                    if not tx_id:
                        tx_id = f"single_{event.event_uuid}"
                    if tx_id not in groups:
                        group_order.append(tx_id)
                    groups[tx_id].append(event)
                
                failed_any = False
                for tx_id in group_order:
                    events_in_tx = groups[tx_id]
                    
                    # Process transaction group atomically
                    success = await process_chain_transaction_group(tx_id, events_in_tx, db, rules)
                    
                    if success:
                        for event in events_in_tx:
                            event.processed_chain = True
                    else:
                        db.rollback()
                        logger.warning(f"Chain execution transaction group failed for {tx_id}. Retrying next loop...")
                        failed_any = True
                        await asyncio.sleep(2)
                        break
                        
                    db.commit()
                
                if failed_any:
                    await asyncio.sleep(1)
                    
            except Exception as e:
                db.rollback()
                logger.error(f"Error in Chain Worker execution loop: {e}")
                await asyncio.sleep(3)
            finally:
                db.close()
        except Exception as e:
            logger.error(f"Database session setup failed in Chain Worker: {e}")
            await asyncio.sleep(5)
