import asyncio
import json
import os
import logging
import importlib
import uuid
from collections import defaultdict

# Logger setup
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("ChainIngestionWorker")

RULES_PATH = os.path.join(os.path.dirname(__file__), "config", "chain_rules.json")

def load_chain_rules():
    if not os.path.exists(RULES_PATH):
        logger.warning(f"Chain rules configuration file not found at {RULES_PATH}. Using empty rules.")
        return []
    try:
        with open(RULES_PATH, "r", encoding="utf-8") as f:
            data = json.load(f)
            return data.get("rules", [])
    except Exception as e:
        logger.error(f"Failed to load chain rules: {e}")
        return []

def execute_custom_mapper(module_name: str, function_name: str, db, payload):
    """
    Dynamically imports a python mapper module and executes the mapping function.
    """
    try:
        module = importlib.import_module(module_name)
        mapper_func = getattr(module, function_name)
        return mapper_func(db, payload)
    except Exception as e:
        logger.error(f"Error executing custom mapper {module_name}.{function_name}: {e}")
        raise e

async def process_chain_transaction_group(tx_id, events, db, rules):
    # 1. Filter out events already generated by chain_ingestion to prevent circular loops
    valid_events = [e for e in events if e.payload.get("source_name") != "chain_ingestion"]
    if not valid_events:
        return True

    # 2. Map of updates grouped by target table
    # target_table -> list of GeneralUpdateItem dicts
    table_updates = defaultdict(list)
    
    # 3. Evaluate rules for this transaction
    # To support batch rules, we group rules by trigger table to execute them efficiently.
    # First, gather trigger tables present in valid_events
    trigger_tables = set(e.table_name for e in valid_events if e.event_type in ["CREATE", "EDIT"])
    
    for table_name in trigger_tables:
        matched_rules = [r for r in rules if r.get("trigger_table") == table_name and r.get("enabled", True)]
        if not matched_rules:
            continue
            
        for rule in matched_rules:
            target_table = rule.get("target_table")
            module_name = rule.get("mapper_module")
            func_name = rule.get("mapper_function")
            is_batch = rule.get("is_batch", False)
            
            try:
                if is_batch:
                    # Collect all payloads for this trigger table in the current transaction group
                    payloads = [e.payload for e in valid_events if e.table_name == table_name and e.event_type in ["CREATE", "EDIT"]]
                    # Pass the whole list to custom mapper
                    target_payload = execute_custom_mapper(module_name, func_name, db, payloads)
                    if target_payload and target_payload.get("updates"):
                        table_updates[target_table].extend(target_payload.get("updates"))
                else:
                    # Single event execution
                    for event in valid_events:
                        if event.table_name == table_name and event.event_type in ["CREATE", "EDIT"]:
                            target_payload = execute_custom_mapper(module_name, func_name, db, event.payload)
                            if target_payload and target_payload.get("updates"):
                                table_updates[target_table].extend(target_payload.get("updates"))
            except Exception as e:
                import traceback
                error_msg = traceback.format_exc()
                logger.error(f"Failed to execute mapper in tx {tx_id} for rule '{rule.get('name')}': {error_msg}")
                return False, error_msg

    # 4. Perform chained batch updates by target table
    if table_updates:
        from database import schemas, crud
        from database.context import request_user, request_transaction_id, request_source
        
        chain_tx_id = f"chain_{tx_id}"
        token_user = request_user.set("chain_worker")
        token_tx = request_transaction_id.set(chain_tx_id)
        token_src = request_source.set("chain_ingestion")
        
        try:
            for target_table, updates_list in table_updates.items():
                batch_data = schemas.GeneralUpdateBatch(
                    updates=updates_list,
                    transaction_id=chain_tx_id,
                    silent=False
                )
                logger.info(f"Executing chained batch updates to '{target_table}' under tx '{chain_tx_id}' (size: {len(updates_list)})")
                
                # Apply updates
                results, changed_cells, created_logs = crud.apply_batch_updates(db, target_table, batch_data)
                
                # 5. Broadcast real-time WebSocket events containing created_logs (Audit History)
                try:
                    from main import manager, inject_system_columns, to_local_str
                    
                    msg_items = []
                    for row, is_new in results:
                        inject_system_columns(row)
                        msg_items.append({
                            "row_id": row.row_id,
                            "is_new": is_new,
                            "data": row.data,
                            "created_at": to_local_str(row.created_at),
                            "updated_at": to_local_str(row.updated_at)
                        })
                        
                    user_name = "chain_worker"
                    
                    if len(msg_items) > 100:
                        msg = {
                            "event": "batch_refresh_required",
                            "table_name": target_table,
                            "change_count": len(msg_items),
                            "transaction_id": chain_tx_id,
                            "created_logs": created_logs
                        }
                    else:
                        msg = {
                            "event": "batch_row_upsert",
                            "table_name": target_table,
                            "items": msg_items,
                            "updated_by": user_name,
                            "transaction_id": chain_tx_id,
                            "created_logs": created_logs
                        }
                    print(msg)
                    await manager.broadcast(json.dumps(msg))
                    logger.info(f"Successfully broadcasted chained update message for '{target_table}' under tx '{chain_tx_id}'.")
                except Exception as ws_err:
                    logger.error(f"Failed to broadcast chained update WebSocket message: {ws_err}")
                    
        except Exception as e:
            import traceback
            error_msg = traceback.format_exc()
            logger.error(f"Failed executing chained batch update for tx {tx_id}: {error_msg}")
            return False, error_msg
        finally:
            request_user.reset(token_user)
            request_transaction_id.reset(token_tx)
            request_source.reset(token_src)
            
    return True, None

async def start_chain_ingestion_worker(db_session_factory):
    logger.info("Initializing Chained Ingestion Worker Daemon...")
    rules = load_chain_rules()
    logger.info(f"Loaded {len(rules)} active chain ingestion rules.")
    
    import sys
    script_dir = os.path.dirname(os.path.abspath(__file__))
    if script_dir not in sys.path:
        sys.path.append(script_dir)
        
    while True:
        try:
            db = db_session_factory()
            try:
                from database.models import DatabaseOutbox
                # Fetch pending outbox records
                pending_events = db.query(DatabaseOutbox).filter(
                    DatabaseOutbox.processed_chain == False
                ).order_by(DatabaseOutbox.id.asc()).limit(200).all()
                
                if not pending_events:
                    await asyncio.sleep(1)
                    continue
                
                # Dynamic fetch guard: if the last element belongs to a transaction, fetch all remaining events of the same tx
                last_event = pending_events[-1]
                last_tx_id = last_event.payload.get("transaction_id")
                if last_tx_id:
                    current_ids = {e.id for e in pending_events}
                    # Fetch other pending candidates to filter in-memory (bypass DB json dialect compatibility issues)
                    candidates = db.query(DatabaseOutbox).filter(
                        DatabaseOutbox.processed_chain == False,
                        ~DatabaseOutbox.id.in_(current_ids)
                    ).limit(10000).all()
                    
                    extra_events = [e for e in candidates if e.payload.get("transaction_id") == last_tx_id]
                    if extra_events:
                        pending_events.extend(extra_events)
                        logger.info(f"Loaded {len(extra_events)} extra events to complete tx '{last_tx_id}' (Total size: {len(pending_events)})")
                
                # Group events by transaction_id
                groups = defaultdict(list)
                group_order = []
                
                for event in pending_events:
                    tx_id = event.payload.get("transaction_id")
                    if not tx_id:
                        tx_id = f"single_{event.event_uuid}"
                    if tx_id not in groups:
                        group_order.append(tx_id)
                    groups[tx_id].append(event)
                
                failed_any = False
                from datetime import datetime
                for tx_id in group_order:
                    events_in_tx = groups[tx_id]
                    
                    # Process transaction group atomically
                    success, error_reason = await process_chain_transaction_group(tx_id, events_in_tx, db, rules)
                    
                    if success:
                        for event in events_in_tx:
                            event.processed_chain = True
                            event.status = "SUCCESS"
                        db.commit()
                    else:
                        db.rollback()
                        
                        # Increment retry count for all events in the failed transaction group
                        failed_permanently_count = 0
                        retrying_count = 0
                        max_retry_num = 0
                        
                        for event in events_in_tx:
                            event.retry_count += 1
                            max_retry_num = max(max_retry_num, event.retry_count)
                            if event.retry_count >= 3:
                                event.status = "FAILED"
                                event.processed_chain = True  # Quarantine from worker queries
                                payload_copy = dict(event.payload) if event.payload else {}
                                payload_copy["error_log"] = {
                                    "failed_at": datetime.now().isoformat(),
                                    "reason": error_reason or f"Mapper execution failed in tx group {tx_id} after 3 retries."
                                }
                                event.payload = payload_copy
                                failed_permanently_count += 1
                            else:
                                event.status = "RETRYING"
                                retrying_count += 1
                                
                        db.commit()
                        
                        if failed_permanently_count > 0:
                            logger.error(f"Transaction {tx_id} permanently failed: {failed_permanently_count} events moved to FAILED status.")
                        if retrying_count > 0:
                            logger.warning(f"Transaction {tx_id} marked for retry: {retrying_count} events set to RETRYING status ({max_retry_num}/3).")
                            
                        failed_any = True
                        break
                
                if failed_any:
                    await asyncio.sleep(1)
                    
            except Exception as e:
                db.rollback()
                logger.error(f"Error in Chain Worker execution loop: {e}")
                await asyncio.sleep(3)
            finally:
                db.close()
        except Exception as e:
            logger.error(f"Database session setup failed in Chain Worker: {e}")
            await asyncio.sleep(5)
