import asyncio
import json
import os
import logging
import importlib
import uuid
import select
import time
from collections import defaultdict

# Setup Unified Logger
from utils.logger import get_process_logger
logger = get_process_logger("Chain", "chain_worker.log")

def blocking_wait(db_session_factory, channel, timeout=30.0):
    db = db_session_factory()
    try:
        engine = db.bind or db.get_bind()
        connection = engine.raw_connection()
        # autocommit 모드로 변경하여 LISTEN 명령이 즉시 반영되게 함
        connection.set_isolation_level(0)
        cursor = connection.cursor()
        cursor.execute(f"LISTEN {channel};")
        
        # select를 활용하여 소켓에 데이터가 들어올 때까지 대기 (CPU 부하 0%)
        r, w, x = select.select([connection], [], [], timeout)
        if r:
            connection.poll()
            while connection.notifies:
                connection.notifies.pop()
            cursor.close()
            connection.close()
            return True
        cursor.close()
        connection.close()
    except Exception as e:
        logger.error(f"PostgreSQL LISTEN/NOTIFY socket wait failed: {e}")
        time.sleep(1.0)
    finally:
        db.close()
        
    return False

async def wait_for_notification(db_session_factory, channel="outbox_event", timeout=30.0):
    """PostgreSQL LISTEN/NOTIFY 기반으로 대기합니다 (타임아웃 기본 30초)."""
    return await asyncio.to_thread(blocking_wait, db_session_factory, channel, timeout)

RULES_PATH = os.path.join(os.path.dirname(__file__), "config", "chain_rules.json")

API_BASE_URL = os.getenv("API_BASE_URL", "http://127.0.0.1:8080")

async def post_event_async(endpoint: str, payload: dict):
    import requests
    url = f"{API_BASE_URL}{endpoint}"
    def do_post():
        try:
            res = requests.post(url, json=payload, timeout=5)
            if not res.ok:
                logger.error(f"[Chain Worker] API notification failed: {url} -> {res.status_code}")
        except Exception as e:
            logger.error(f"[Chain Worker] Failed to send API notification: {e}")
    await asyncio.to_thread(do_post)

def load_chain_rules():
    if not os.path.exists(RULES_PATH):
        logger.warning(f"Chain rules configuration file not found at {RULES_PATH}. Using empty rules.")
        return []
    try:
        with open(RULES_PATH, "r", encoding="utf-8") as f:
            data = json.load(f)
            return data.get("rules", [])
    except Exception as e:
        logger.error(f"Failed to load chain rules: {e}")
        return []

def execute_custom_mapper(module_name: str, function_name: str, db, payload):
    """
    Dynamically imports a python mapper module and executes the mapping function.
    """
    try:
        module = importlib.import_module(module_name)
        mapper_func = getattr(module, function_name)
        return mapper_func(db, payload)
    except Exception as e:
        logger.error(f"Error executing custom mapper {module_name}.{function_name}: {e}")
        raise e

async def process_chain_transaction_group(tx_id, events, db, rules):
    # 1. Filter out events already generated by chain_ingestion to prevent circular loops
    valid_events = [e for e in events if e.payload.get("source_name") != "chain_ingestion"]
    if not valid_events:
        return True, None

    # 2. Map of updates grouped by target table
    # target_table -> list of GeneralUpdateItem dicts
    table_updates = defaultdict(list)
    
    # 3. Evaluate rules for this transaction
    # To support batch rules, we group rules by trigger table to execute them efficiently.
    # First, gather trigger tables present in valid_events
    trigger_tables = set(e.table_name for e in valid_events if e.event_type in ["CREATE", "EDIT"])
    
    for table_name in trigger_tables:
        matched_rules = [r for r in rules if r.get("trigger_table") == table_name and r.get("enabled", True)]
        if not matched_rules:
            continue
            
        for rule in matched_rules:
            target_table = rule.get("target_table")
            module_name = rule.get("mapper_module")
            func_name = rule.get("mapper_function")
            is_batch = rule.get("is_batch", False)
            
            try:
                if is_batch:
                    # Collect all payloads for this trigger table in the current transaction group
                    payloads = [e.payload for e in valid_events if e.table_name == table_name and e.event_type in ["CREATE", "EDIT"]]
                    # Pass the whole list to custom mapper
                    target_payload = execute_custom_mapper(module_name, func_name, db, payloads)
                    if target_payload and target_payload.get("updates"):
                        table_updates[target_table].extend(target_payload.get("updates"))
                else:
                    # Single event execution
                    for event in valid_events:
                        if event.table_name == table_name and event.event_type in ["CREATE", "EDIT"]:
                            target_payload = execute_custom_mapper(module_name, func_name, db, event.payload)
                            if target_payload and target_payload.get("updates"):
                                table_updates[target_table].extend(target_payload.get("updates"))
            except Exception as e:
                import traceback
                error_msg = traceback.format_exc()
                logger.error(f"Failed to execute mapper in tx {tx_id} for rule '{rule.get('name')}': {error_msg}")
                return False, error_msg

    # 4. Perform chained batch updates by target table
    if table_updates:
        from database import schemas, crud
        from database.context import request_user, request_transaction_id, request_source
        
        chain_tx_id = f"chain_{tx_id}"
        token_user = request_user.set("chain_worker")
        token_tx = request_transaction_id.set(chain_tx_id)
        token_src = request_source.set("chain_ingestion")
        
        try:
            for target_table, updates_list in table_updates.items():
                batch_data = schemas.GeneralUpdateBatch(
                    updates=updates_list,
                    transaction_id=chain_tx_id,
                    silent=False
                )
                logger.info(f"Executing chained batch updates to '{target_table}' under tx '{chain_tx_id}' (size: {len(updates_list)})")
                
                # Apply updates
                results, changed_cells, created_logs = crud.apply_batch_updates(db, target_table, batch_data)
                
                # 5. Route WebSocket events and Audit History to the web server
                try:
                    from main import to_local_str
                    
                    cfg = crud.TABLE_CONFIG.get(target_table, {})
                    col_types = cfg.get("column_types", {})
                    user_cols = [c for c in col_types.keys() if c not in ["created_at", "updated_at"]]

                    msg_items = []
                    for row, is_new in results:
                        c_at_str = to_local_str(row.created_at)
                        u_at_str = to_local_str(row.updated_at)
                        
                        r_data = {}
                        for col in user_cols:
                            val = getattr(row, col)
                            if val is None:
                                val = {"value": None, "is_overwrite": False, "sources": {}, "updated_by": "system"}
                            r_data[col] = val
                        r_data["created_at"] = {"value": c_at_str, "is_overwrite": False, "sources": {}, "updated_by": "system"}
                        r_data["updated_at"] = {"value": u_at_str, "is_overwrite": False, "sources": {}, "updated_by": "system"}
                        
                        msg_items.append({
                            "row_id": row.row_id,
                            "is_new": is_new,
                            "data": r_data,
                            "created_at": c_at_str,
                            "updated_at": u_at_str
                        })
                        
                    user_name = "chain_worker"
                    
                    # Ensure created_logs has clean string timestamps
                    serialized_logs = []
                    if created_logs:
                        from datetime import datetime
                        for log in created_logs:
                            log_copy = dict(log)
                            ts = log_copy.get("timestamp")
                            if ts is not None and isinstance(ts, datetime):
                                log_copy["timestamp"] = ts.isoformat()
                            serialized_logs.append(log_copy)

                    if len(msg_items) > 100:
                        msg = {
                            "event": "batch_refresh_required",
                            "table_name": target_table,
                            "change_count": len(msg_items),
                            "transaction_id": chain_tx_id,
                            "created_logs": serialized_logs
                        }
                    else:
                        msg = {
                            "event": "batch_row_upsert",
                            "table_name": target_table,
                            "items": msg_items,
                            "updated_by": user_name,
                            "transaction_id": chain_tx_id,
                            "created_logs": serialized_logs
                        }
                    await post_event_async("/internal/events/broadcast", msg)
                    logger.info(f"Successfully sent chained update event to web server for '{target_table}' under tx '{chain_tx_id}'.")
                except Exception as ws_err:
                    logger.error(f"Failed to post chained update notification: {ws_err}")
                    
        except Exception as e:
            import traceback
            error_msg = traceback.format_exc()
            logger.error(f"Failed executing chained batch update for tx {tx_id}: {error_msg}")
            return False, error_msg
        finally:
            request_user.reset(token_user)
            request_transaction_id.reset(token_tx)
            request_source.reset(token_src)
            
    return True, None

def reload_worker_process_cache():
    """체인 워커 프로세스의 동적 모듈 캐시(mappers, pipeline plugins)를 명시적으로 무효화합니다."""
    import sys
    
    # Remove custom mappers from sys.modules cache
    mapper_keys = [k for k in sys.modules.keys() if k.startswith("mappers.")]
    for k in mapper_keys:
        sys.modules.pop(k, None)
        
    # Remove pipeline plugin parsers from sys.modules cache
    plugin_keys = [k for k in sys.modules.keys() if k.startswith("pipeline_plugin_")]
    for k in plugin_keys:
        sys.modules.pop(k, None)
        
    logger.info("[Reload] Chain worker modules cache cleared.")

async def start_chain_ingestion_worker(db_session_factory):
    logger.info("Initializing Chained Ingestion Worker Daemon...")
    rules = load_chain_rules()
    logger.info(f"Loaded {len(rules)} active chain ingestion rules.")
    
    last_reload_event_id = 0
    
    import sys
    script_dir = os.path.dirname(os.path.abspath(__file__))
    if script_dir not in sys.path:
        sys.path.append(script_dir)
        
    while True:
        try:
            db = db_session_factory()
            try:
                from database.models import DatabaseOutbox
                
                # Check for SYSTEM_RELOAD outbox event to reload configs and code on-demand
                latest_reload = db.query(DatabaseOutbox).filter(
                    DatabaseOutbox.event_type == "SYSTEM_RELOAD"
                ).order_by(DatabaseOutbox.id.desc()).first()
                
                if latest_reload and latest_reload.id > last_reload_event_id:
                    # Sync tracker id
                    last_reload_event_id = latest_reload.id
                    logger.info(f"[Reload] SYSTEM_RELOAD trigger detected (Event ID: {latest_reload.id}). Reloading configurations...")
                    # 1. Reload dynamic modules cache
                    reload_worker_process_cache()
                    # 2. Reload chain rules configurations from disk
                    rules = load_chain_rules()
                    logger.info(f"[Reload] Loaded {len(rules)} active chain ingestion rules.")
                    
                    # Mark the trigger event as SUCCESS in this tx if it is not processed yet
                    # (This event only serves as IPC notify signal, does not execute mappers)
                    if latest_reload.processed_chain == False:
                        latest_reload.processed_chain = True
                        latest_reload.status = "SUCCESS"
                        db.commit()

                # Fetch pending outbox records
                pending_events = db.query(DatabaseOutbox).filter(
                    DatabaseOutbox.processed_chain == False
                ).order_by(DatabaseOutbox.id.asc()).limit(200).all()
                
                if not pending_events:
                    await wait_for_notification(db_session_factory, "outbox_event", 30.0)
                    continue
                
                # Dynamic fetch guard: if the last element belongs to a transaction, fetch all remaining events of the same tx
                # 1. First unpack/normalize all payloads in pending_events and mark/filter SCHEDULER_RUN_NOW control events
                normalized_events = []
                import json
                for event in pending_events:
                    payload_data = event.payload
                    if isinstance(payload_data, str):
                        try:
                            payload_data = json.loads(payload_data)
                        except Exception:
                            payload_data = {}
                    
                    if event.event_type == "SCHEDULER_RUN_NOW":
                        continue
                        
                    event._parsed_payload = payload_data
                    normalized_events.append(event)

                if not normalized_events:
                    continue

                last_event = normalized_events[-1]
                last_tx_id = last_event._parsed_payload.get("transaction_id") if isinstance(last_event._parsed_payload, dict) else None
                if last_tx_id:
                    current_ids = {e.id for e in normalized_events}
                    candidates = db.query(DatabaseOutbox).filter(
                        DatabaseOutbox.processed_chain == False,
                        ~DatabaseOutbox.id.in_(current_ids)
                    ).limit(10000).all()
                    
                    extra_events = []
                    for e in candidates:
                        e_pay = e.payload
                        if isinstance(e_pay, str):
                            try:
                                e_pay = json.loads(e_pay)
                            except Exception:
                                e_pay = {}
                        if e_pay.get("transaction_id") == last_tx_id:
                            e._parsed_payload = e_pay
                            extra_events.append(e)
                            
                    if extra_events:
                        normalized_events.extend(extra_events)
                        logger.info(f"Loaded {len(extra_events)} extra events to complete tx '{last_tx_id}' (Total size: {len(normalized_events)})")
                
                # Group events by transaction_id
                groups = defaultdict(list)
                group_order = []
                
                for event in normalized_events:
                    tx_id = event._parsed_payload.get("transaction_id") if isinstance(event._parsed_payload, dict) else None
                    if not tx_id:
                        tx_id = f"single_{event.event_uuid}"
                    if tx_id not in groups:
                        group_order.append(tx_id)
                    groups[tx_id].append(event)
                
                failed_any = False
                from datetime import datetime
                for tx_id in group_order:
                    events_in_tx = groups[tx_id]
                    
                    # Process transaction group atomically
                    success, error_reason = await process_chain_transaction_group(tx_id, events_in_tx, db, rules)
                    
                    if success:
                        for event in events_in_tx:
                            event.processed_chain = True
                            event.status = "SUCCESS"
                        db.commit()
                    else:
                        db.rollback()
                        
                        # Increment retry count for all events in the failed transaction group
                        failed_permanently_count = 0
                        retrying_count = 0
                        max_retry_num = 0
                        
                        for event in events_in_tx:
                            event.retry_count += 1
                            max_retry_num = max(max_retry_num, event.retry_count)
                            if event.retry_count >= 3:
                                event.status = "FAILED"
                                event.processed_chain = True  # Quarantine from worker queries
                                payload_copy = dict(event.payload) if event.payload else {}
                                payload_copy["error_log"] = {
                                    "failed_at": datetime.now().isoformat(),
                                    "reason": error_reason or f"Mapper execution failed in tx group {tx_id} after 3 retries."
                                }
                                event.payload = payload_copy
                                failed_permanently_count += 1
                            else:
                                event.status = "RETRYING"
                                retrying_count += 1
                                
                        db.commit()
                        
                        if failed_permanently_count > 0:
                            logger.error(f"Transaction {tx_id} permanently failed: {failed_permanently_count} events moved to FAILED status.")
                        if retrying_count > 0:
                            logger.warning(f"Transaction {tx_id} marked for retry: {retrying_count} events set to RETRYING status ({max_retry_num}/3).")
                            
                        failed_any = True
                        break
                
                if failed_any:
                    await asyncio.sleep(1)
                    
            except Exception as e:
                db.rollback()
                logger.error(f"Error in Chain Worker execution loop: {e}")
                await asyncio.sleep(3)
            finally:
                db.close()
        except Exception as e:
            logger.error(f"Database session setup failed in Chain Worker: {e}")
            await asyncio.sleep(5)
