// ═══════════════════════════════════════════════════════════════════════════════
// 🔴🔴 DEAD CODE. DO NOT IMPORT THIS FROM ANYTHING THAT SHIPS. 🔴🔴
//
// This was the temporary stand-in for layers 5 and 7 while `verdict.js` was being written.
// `verdict.js` has landed and `verdict_bridge.js` now points at it. NOTHING under `src/`
// imports this file any more, and nothing may.
//
// IT IS KEPT ON DISK FOR EXACTLY ONE REASON: `client2/tests/alignment_verdict_harness.mjs`
// imports it as the BEFORE side of its comparison -- it scores the replacement against the
// thing it replaced. Deleting the file killed that harness outright, which is why it is back.
// When that harness stops needing the comparison, delete this file in the same change.
//
// ⚠️ IT CONTAINS A REAL DEFECT, LEFT IN PLACE ON PURPOSE so the harness can keep scoring that
//    `verdict.js` does not reproduce it: `finiteOrNull` below now guards null/undefined/'' but
//    the ORIGINAL shipped spelling used bare `Number(v)`, and `Number(null) === 0`, so an
//    ABSENT `min_margin_dies` became a threshold of zero -- "always rank". That is I4 (a
//    plausible default impersonating a declaration) living inside the guard against I4.
//    `verdict.js` rejects null / undefined / '' / boolean explicitly and pins all four
//    spellings.
//
// Layer 5 and 7 questions go to `verdict.js`. Do not edit this file to fix behaviour; fix it
// there.
// ═══════════════════════════════════════════════════════════════════════════════

export const VERDICT = Object.freeze({
  WINNER: 'winner',
  INDISTINGUISHABLE: 'indistinguishable',
  NOT_SCORABLE: 'not_scorable',
});

export const REASON = Object.freeze({
  NO_THRESHOLDS: 'no_thresholds',
  NO_SCORINGS: 'no_scorings',
  TOO_FEW_DISCRIMINATING: 'too_few_discriminating',
  MARGIN_TOO_SMALL: 'margin_too_small',
  SERVER_REFUSED: 'server_refused',
});

export function decideVerdict(scorings, thresholds, context) {
  const detail = context && context.refusalDetail ? String(context.refusalDetail) : '';
  if (detail) {
    return frozen(VERDICT.NOT_SCORABLE, REASON.SERVER_REFUSED, { refusalDetail: detail });
  }

  const usable = (Array.isArray(scorings) ? scorings : []).filter(isScorable);
  if (usable.length === 0) {
    return frozen(VERDICT.NOT_SCORABLE, REASON.NO_SCORINGS, {});
  }

  const minMargin = finiteOrNull(thresholds && thresholds.min_margin_dies);
  const minDiscriminating = finiteOrNull(thresholds && thresholds.min_discriminating_dies);
  if (minMargin === null || minDiscriminating === null) {
    return frozen(VERDICT.NOT_SCORABLE, REASON.NO_THRESHOLDS, {});
  }

  const ranked = usable.slice().sort((a, b) => (
    b.agree - a.agree || String(a.candidate_id).localeCompare(String(b.candidate_id))
  ));
  const rankedIds = Object.freeze(ranked.map(s => s.candidate_id));

  const top = ranked[0];
  const runnerUp = ranked[1] || null;
  const marginDies = runnerUp ? top.agree - runnerUp.agree : top.agree;
  const discriminating = top.discriminating;

  if (discriminating < minDiscriminating) {
    return frozen(VERDICT.NOT_SCORABLE, REASON.TOO_FEW_DISCRIMINATING, {
      rankedIds, discriminating, minDiscriminating, marginDies,
    });
  }
  if (marginDies < minMargin) {
    const tied = ranked.filter(s => top.agree - s.agree < minMargin).length;
    return frozen(VERDICT.INDISTINGUISHABLE, REASON.MARGIN_TOO_SMALL, {
      rankedIds, discriminating, marginDies, minMargin, tiedCount: tied,
    });
  }
  return frozen(VERDICT.WINNER, null, {
    rankedIds, winnerId: top.candidate_id, discriminating, marginDies, minMargin,
  });
}

function isScorable(s) {
  return !!s
    && Number.isFinite(Number(s.agree))
    && Number.isFinite(Number(s.discriminating))
    && typeof s.candidate_id === 'string';
}

function finiteOrNull(v) {
  if (v === null || v === undefined || v === '') return null;
  const n = Number(v);
  return Number.isFinite(n) ? n : null;
}

function frozen(kind, reason, extra) {
  return Object.freeze({
    kind,
    reason: reason || null,
    winnerId: extra.winnerId || null,
    rankedIds: extra.rankedIds || Object.freeze([]),
    marginDies: Number.isFinite(extra.marginDies) ? extra.marginDies : null,
    discriminating: Number.isFinite(extra.discriminating) ? extra.discriminating : null,
    minMargin: Number.isFinite(extra.minMargin) ? extra.minMargin : null,
    minDiscriminating: Number.isFinite(extra.minDiscriminating) ? extra.minDiscriminating : null,
    tiedCount: Number.isFinite(extra.tiedCount) ? extra.tiedCount : null,
    refusalDetail: extra.refusalDetail || null,
  });
}
